version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    directory: "/"
    grouping:
      - group: "production"
        match:
          - dependency-type: "all"
          - update-type: "widen"
      - group: "development"
        match:
          - dependency-type: "dev"
