env:
  node: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:n/recommended
  - plugin:mocha/recommended
parserOptions:
  ecmaVersion: latest
rules:
  semi: [error, always]
  indent: [error, 2]
  no-var: [error]
  prefer-const: [warn]
  no-use-before-define: [warn]
  prefer-destructuring: [error]
  space-in-parens: [warn, never]
  object-curly-spacing: [warn, always]
  "n/no-unpublished-require": [error, { allowModules: ["aws-sdk"]}]
