env:
  node: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:n/recommended
  - plugin:jest/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  no-var: [error]
  prefer-const: [warn]
  no-use-before-define: [warn]
  prefer-destructuring: [error]
  "n/no-unpublished-require": [error, { allowModules: ["aws-sdk"] }]
