name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
          - 'lts/*'
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
