name: Update IP Ranges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  update-ranges:
    runs-on: ubuntu-latest
    name: Update ranges
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: Cache IP Ranges
        id: cache-ipranges
        uses: actions/cache@v3
        with:
          path: ./ipranges-sync/
          key: ${{ runner.os }}-ipranges
      - run: aws s3 sync s3://iprangesproject-iprangess3bucket-1xpm6odtii6lr ./ipranges-sync/
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
          known_hosts: unnecessary
      - run: |
          git checkout -B update-ranges --track
          git pull
          git config --global user.name "dmgress[update_ranges]"
          git config --global user.email "dmgress@users.noreply.github.com"
          ./history.sh
          git push origin HEAD
